apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qIrnJtJqX1wqgTy33G9PuS3JEIBEXPfx88/zSWz7HXakr/7GU3DfrQ==,iv:K89bsjW/wyVUNoASUQTLBatHa2EednuA5UpoPdKBgHM=,tag:UJTynkUrFluxQRuM17qJgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mgtjr7s03uesl4l2f4mt42q8p0xp44g57yqu8kaejkgkujw89afq04rcay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL1lpU2I5SGZZc29CY2hl
            aGNoL3hOOEFzYktmWHZpVnRKRFRBNzVRd21FCmR4YW5IVk1YVkdPc05GbHZvdUZ1
            dkFPL1NmczZ0RHZoaDdDQ3NGUEtPOGsKLS0tIC9BR3ozdDVTRlV4TnI4UDQ4eXBm
            WXV0Z08vbWtxcU5RR05yUmtWaU9wYzQKZR6roOnyQh7WW79NzQabu2l82/LqagxT
            vXrqk7S+1fJWKzeVE86a9oxiFyJDW95ezFOLL+10h8TtIC5NubKfvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T02:50:14Z"
    mac: ENC[AES256_GCM,data:UwQCQ2insi7tpUo71NEvnxUFqr51Y48VyzflsgkfjMJNTx1gK7+dAdkMdkcgx2Wfgq2+6CEIZmUHdnAIprLqeVTl+GsVy3iWeS4+PtdzE7TeDjZ60tunBTrPAvQQld7U59ae6NKVn4aqgenUyUEtfwN4TUBVMcdO4PSi02mIsJk=,iv:YLDW9JdFc6B24AVeoofxlCFWs8ezxsGnnttZ3wo7PTc=,tag:cnrRM1QEwSGsWQKOWcW4xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
