---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.2.58"
  METALLB_LB_RANGE: "192.168.2.60-192.168.2.120"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.60"
  METALLB_INGRESS_ADDR: "192.168.2.61"
